import './globals.css'
import localFont from '@next/font/local'

const sohne = localFont({
  src: [
    {
      path: '../../public/fonts/sohne.woff',
      weight: '400'
    },   
  ],
  variable: '--font-sohne'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={`${sohne.variable} font-sans`}>{children}</body>
    </html>
  )
}
